// Generated by gencpp from file scout_msgs/ScoutLightCmd.msg
// DO NOT EDIT!


#ifndef SCOUT_MSGS_MESSAGE_SCOUTLIGHTCMD_H
#define SCOUT_MSGS_MESSAGE_SCOUTLIGHTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scout_msgs
{
template <class ContainerAllocator>
struct ScoutLightCmd_
{
  typedef ScoutLightCmd_<ContainerAllocator> Type;

  ScoutLightCmd_()
    : enable_cmd_light_control(false)
    , front_mode(0)
    , front_custom_value(0)
    , rear_mode(0)
    , rear_custom_value(0)  {
    }
  ScoutLightCmd_(const ContainerAllocator& _alloc)
    : enable_cmd_light_control(false)
    , front_mode(0)
    , front_custom_value(0)
    , rear_mode(0)
    , rear_custom_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_cmd_light_control_type;
  _enable_cmd_light_control_type enable_cmd_light_control;

   typedef uint8_t _front_mode_type;
  _front_mode_type front_mode;

   typedef uint8_t _front_custom_value_type;
  _front_custom_value_type front_custom_value;

   typedef uint8_t _rear_mode_type;
  _rear_mode_type rear_mode;

   typedef uint8_t _rear_custom_value_type;
  _rear_custom_value_type rear_custom_value;



  enum {
    LIGHT_CONST_OFF = 0u,
    LIGHT_CONST_ON = 1u,
    LIGHT_BREATH = 2u,
    LIGHT_CUSTOM = 3u,
  };


  typedef boost::shared_ptr< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ScoutLightCmd_

typedef ::scout_msgs::ScoutLightCmd_<std::allocator<void> > ScoutLightCmd;

typedef boost::shared_ptr< ::scout_msgs::ScoutLightCmd > ScoutLightCmdPtr;
typedef boost::shared_ptr< ::scout_msgs::ScoutLightCmd const> ScoutLightCmdConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scout_msgs::ScoutLightCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scout_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'scout_msgs': ['/home/yyw/sim_scout_ws/src/scout_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4efcbd363caf677fd8138923f982df13";
  }

  static const char* value(const ::scout_msgs::ScoutLightCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4efcbd363caf677fULL;
  static const uint64_t static_value2 = 0xd8138923f982df13ULL;
};

template<class ContainerAllocator>
struct DataType< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scout_msgs/ScoutLightCmd";
  }

  static const char* value(const ::scout_msgs::ScoutLightCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LIGHT_CONST_OFF = 0\n\
uint8 LIGHT_CONST_ON = 1\n\
uint8 LIGHT_BREATH = 2\n\
uint8 LIGHT_CUSTOM = 3\n\
\n\
bool enable_cmd_light_control\n\
uint8 front_mode\n\
uint8 front_custom_value\n\
uint8 rear_mode\n\
uint8 rear_custom_value\n\
";
  }

  static const char* value(const ::scout_msgs::ScoutLightCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_cmd_light_control);
      stream.next(m.front_mode);
      stream.next(m.front_custom_value);
      stream.next(m.rear_mode);
      stream.next(m.rear_custom_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScoutLightCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scout_msgs::ScoutLightCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scout_msgs::ScoutLightCmd_<ContainerAllocator>& v)
  {
    s << indent << "enable_cmd_light_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_cmd_light_control);
    s << indent << "front_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_mode);
    s << indent << "front_custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_custom_value);
    s << indent << "rear_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rear_mode);
    s << indent << "rear_custom_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rear_custom_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOUT_MSGS_MESSAGE_SCOUTLIGHTCMD_H
